// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdminUser = "admin_user"

// AdminUser 管理员表
type AdminUser struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键-管理员ID" json:"id"` // 主键-管理员ID
	Name      string `gorm:"column:name;not null;comment:管理员名称" json:"name"`                     // 管理员名称
	Username  string `gorm:"column:username;not null;comment:管理员用户名" json:"username"`            // 管理员用户名
	Mobile    string `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                   // 手机号
	Password  string `gorm:"column:password;not null;comment:管理员密码" json:"password"`             // 管理员密码
	Status    int32  `gorm:"column:status;not null;comment:状态：1-正常，-1-禁用" json:"status"`         // 状态：1-正常，-1-禁用
	CreatedAt int64  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt int64  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`          // 更新时间
	DeletedAt *int64 `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                   // 删除时间
	CreateBy  int64  `gorm:"column:create_by;not null;comment:创建人" json:"create_by"`             // 创建人
	UpdateBy  int64  `gorm:"column:update_by;not null;comment:更新人" json:"update_by"`             // 更新人
	Sex       int32  `gorm:"column:sex;not null;default:3;comment:性别：1-男，2-女,3-其他" json:"sex"`   // 性别：1-男，2-女,3-其他
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
